[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[variables]
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"
PORT = "3000"

[start]
cmd = "node .next/standalone/server.js"

