[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = ["npm start"]

[staticAssets]
paths = ["public"]

[variables]
NODE_ENV = "production"

